# Generated by Django 2.0.8 on 2019-03-31 14:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.FileField(default=None, upload_to='media/UserFiles')),
                ('uploaded_on', models.DateTimeField(default=datetime.datetime(2019, 3, 31, 14, 39, 56, 713044, tzinfo=utc))),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=265, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='media/UserImages')),
                ('uploaded_on', models.DateTimeField(default=datetime.datetime(2019, 3, 31, 14, 39, 56, 710075, tzinfo=utc))),
                ('image_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
